<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="dev_user" tests="4" time="0.124">
  <testsuite name="用户注册1.3" id="d45e31f4-8b96-4353-82af-06cf9137e155" timestamp="2023-02-11T09:51:47.058Z" tests="2" failures="0" errors="0" time="0.082">
    <testcase name="Response time is less than 1000ms" time="0.082" classname="DevUser"/>
    <testcase name="Status code is 200" time="0.082" classname="DevUser"/>
  </testsuite>
  <testsuite name="获取验证码" id="302e2e0e-88ca-4ecf-91c2-6fd69f1bd4a1" timestamp="2023-02-11T09:51:47.058Z" tests="2" failures="0" errors="0" time="0.017">
    <testcase name="Response time is less than 1000ms" time="0.017" classname="DevUser"/>
    <testcase name="Status code is 200" time="0.017" classname="DevUser"/>
  </testsuite>
  <testsuite name="用户列表1.0" id="8d76772c-a9c9-4aa4-ade9-6098d6c1bd1d" timestamp="2023-02-11T09:51:47.058Z" tests="2" failures="0" errors="0" time="0.017">
    <testcase name="Response time is less than 1000ms" time="0.017" classname="DevUser"/>
    <testcase name="Status code is 200" time="0.017" classname="DevUser"/>
  </testsuite>
  <testsuite name="用户登录1.3" id="75d64dc7-95db-4914-ad64-03a2d719f38d" timestamp="2023-02-11T09:51:47.058Z" tests="3" failures="1" errors="1" time="0.008">
    <system-err><![CDATA[Iteration: 0

---
testScriptError: AssertionFailure: Your test name
    at postProcessContext (C:\Users\dreamfuture\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:40:17)
    at PostmanCollectionRun.<anonymous> (C:\Users\dreamfuture\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:488:31)
    at PostmanSandbox.<anonymous> (C:\Users\dreamfuture\AppData\Roaming\npm\node_modules\newman\node_modules\postman-sandbox\lib\index.js:107:13)
    at Object.onceWrapper (node:events:628:26)
    at PostmanSandbox.emit (node:events:513:28)
    at context.__uvm_emit (C:\Users\dreamfuture\AppData\Roaming\npm\node_modules\newman\node_modules\uvm\lib\bridge.js:71:21)
    at Object.dispatch (evalmachine.<anonymous>:20:13)
    at Object.<anonymous> (evalmachine.<anonymous>:58:7101)
    at t.exports.terminate (evalmachine.<anonymous>:58:18217)
    at evalmachine.<anonymous>:58:5853
    at evalmachine.<anonymous>:58:1789089
    at u.exec (evalmachine.<anonymous>:58:1788668)
    at t.exports (evalmachine.<anonymous>:58:5743)
    at Object.<anonymous> (evalmachine.<anonymous>:58:7440)
    at evalmachine.<anonymous>:15:26
    at Array.forEach (<anonymous>)
---
]]></system-err>
    <testcase name="Response time is less than 1000ms" time="0.008" classname="DevUser"/>
    <testcase name="Status code is 200" time="0.008" classname="DevUser"/>
    <testcase name="Your test name" time="0.008" classname="DevUser">
      <failure type="AssertionFailure" message="expected '用户账户或密码错误，登录失败' to deeply equal '成功'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: a08a8fa7-c02b-44d2-b4ac-72d13c0739d0.]]>
        <![CDATA[Collection name: dev_user.]]>
        <![CDATA[Request name: 用户登录1.3.]]>
        <![CDATA[Test description: Your test name.]]>
        <![CDATA[Error message: expected '用户账户或密码错误，登录失败' to deeply equal '成功'.]]>
        <![CDATA[Stacktrace: AssertionError: expected '用户账户或密码错误，登录失败' to deeply equal '成功'
   at Object.eval sandbox-script.js:3:4).]]>
      </failure>
    </testcase>
  </testsuite>
</testsuites>